name: Bitbucket Cloud to GitHub Enterprise Cloud
description: Perform a migration from Bitbucket Cloud to GitHub Enterprise Cloud
title: 'Bitbucket Cloud to GitHub Enterprise Cloud migration'
labels:
  - 'migration'
  - 'bitbucket-cloud'
body:
  - type: textarea
    id: repositories
    attributes:
      label: Repositories
      description:
        Please enter the repositories that you would like to migrate from
        Bitbucket Cloud to GitHub Enterprise Cloud
      render: CSV
      placeholder: |
        project0,repo1
        project1,repo2
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Target repository visibility
      description:
        Please select the visibility for the repositories on GitHub Enterprise
        Cloud after they have been migrated
      options:
        - Private
        - Internal
    validations:
      required: true
