name: Prepare Migration

on:
  issues:
    types:
      - opened
      - edited

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'issues' &&
      (github.event.action == 'opened' || github.event.action == 'edited') &&
      contains(github.event.issue.labels.*.name, 'migration')

    steps:
      - name: Check out scripts
        uses: actions/checkout@v3

      - name: Post prepare message
        uses: actions/github-script@v6
        with:
          script: |
            const prepare = require('./.github/scripts/prepare.js')
            const options = { targetOrganization: '${{ vars.GHEC_TARGET_ORGANIZATION }}' }
            await prepare({github, context, core, options})

      - name: Post failure message
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            const body = `😢 The issue body could not be parsed. Please edit the issue body or open a new issue using an issue template.

            [View workflow run for details](${context.payload.repository.html_url}/actions/runs/${context.runId})
            `

            await github.rest.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: '${{ github.REPOSITORY_OWNER }}',
              repo: '${{ github.event.repository.name }}',
              body: body
            })
