name: Migration from Bitbucket Cloud

on:
  issue_comment:
    types:
      - created

jobs:
  migrate:
    if: |
      contains(toJson(github.event.*.labels.*.name), 'migration') &&
      contains(toJson(github.event.issue.labels.*.name), 'bitbucket-cloud')
    uses: ./.github/workflows/03-shared-bitbucket-cloud-export-import.yml
    secrets:
      BITBUCKET_CLOUD_ADMIN_TOKEN: ${{ secrets.BITBUCKET_CLOUD_ADMIN_TOKEN }}
      GHEC_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
