name: Migration from Bitbucket Cloud

on:
  issue_comment:
    types:
      - created

jobs:
  export:
    if: |
      contains(toJson(github.event.*.labels.*.name), 'migration') &&
      contains(toJson(github.event.issue.labels.*.name), 'bitbucket-cloud')
    uses: ./.github/workflows/03-shared-bitbucket-cloud-export.yml
    secrets:
      BITBUCKET_CLOUD_ADMIN_TOKEN: ${{ secrets.BITBUCKET_CLOUD_ADMIN_TOKEN }}
      BITBUCKET_CLOUD_WORKSPACE: ${{ vars.BITBUCKET_CLOUD_WORKSPACE }}

  #import:
  #  needs: export
  #  uses: ./.github/workflows/04-shared-github-enterprise-cloud-import.yml
  #  with:
  #    user-mappings-path: ../../user-mappings.csv
  #  secrets:
  #    BITBUCKET_CLOUD_USER_MAPPING_URL: ${{ vars.BBS_URL }}/users/
  #    GHEC_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
  #    GHEC_TARGET_ORGANIZATION: ${{ vars.GHEC_TARGET_ORGANIZATION }}
