name: Migration from Bitbucket Server

on:
  issue_comment:
    types:
      - created

jobs:
  export:
    if:
      contains(toJson(github.event.*.labels.*.name), 'migration') &&
      contains(toJson(github.event.issue.labels.*.name), 'bitbucket-server')
    uses: ./.github/workflows/03-shared-bitbucket-server-export.yml
    with:
      setup-ruby: true
    secrets:
      BITBUCKET_API_PRIVATE_TOKEN: ${{ secrets.BBS_ADMIN_TOKEN }}
      BITBUCKET_API_ENDPOINT: '${{ vars.BBS_URL }}/rest/api/latest'

  import:
    needs: export
    uses: ./.github/workflows/04-shared-github-enterprise-cloud-import.yml
    with:
      user-mappings-path: ../../user-mappings.csv
    secrets:
      BBS_USER_MAPPING_URL: ${{ vars.BBS_URL }}/users/
      GHEC_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
      GHEC_TARGET_ORGANIZATION: ${{ vars.GHEC_TARGET_ORGANIZATION }}
