name: Migration from Bitbucket Server

on:
  issue_comment:
    types:
      - created

jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Output Labels Context
        env:
          LABELS: ${{ toJson(github.event.*.labels) }}
        run: echo "$LABELS"
      - name: Output Names Context
        env:
          NAMES: ${{ toJson(github.event.*.labels.*.name) }}
        run: echo "$NAMES"
      - name: Output Test
        run: echo "${{ contains(toJson(github.event.*.labels.*.name),'migration') }}"
      - name: Output Test2
        run: echo "${{ contains(github.event.*.labels.*.name,'migration') }}"
      - name: output test3
        run: echo "${{ contains(toJson(github.event.*.labels.*.name), 'migration') && contains(toJson(github.event.issue.labels.*.name), 'bitbucket-server') }}"

  export:
    #if: ${{ contains(toJson(github.event.*.labels.*.name), 'migration') }} && ${{ contains(toJson(github.event.issue.labels.*.name), 'bitbucket-server') }}
    uses: ./.github/workflows/03-shared-bitbucket-server-export.yml
    with:
      setup-ruby: true
    secrets:
      BITBUCKET_API_PRIVATE_TOKEN: ${{ secrets.BBS_ADMIN_TOKEN }}
      BITBUCKET_API_ENDPOINT: '${{ vars.BBS_URL }}/rest/api/latest'

  import:
    needs: export
    uses: ./.github/workflows/04-shared-github-enterprise-cloud-import.yml
    with:
      user-mappings-path: ../../user-mappings.csv
    secrets:
      BBS_USER_MAPPING_URL: ${{ vars.BBS_URL }}/users/
      GHEC_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
      GHEC_TARGET_ORGANIZATION: ${{ vars.GHEC_TARGET_ORGANIZATION }}
