name: Shared Bitbucket Cloud Export

on:
  workflow_call:
    inputs:
      migration-guid:
        default: migration-archive-${{ github.event.issue.number }}
        type: string
    secrets:
      BITBUCKET_CLOUD_ADMIN_TOKEN:
        required: true
      GHEC_ADMIN_TOKEN:
        required: true

jobs:
  export:
    name: Export
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'issue_comment' &&
      (startsWith(github.event.comment.body, '/run-dry-run-migration') || startsWith(github.event.comment.body, '/run-production-migration'))

    env:
      MIGRATION_GUID: ${{ inputs.migration-guid }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update issue with running status
        uses: actions/github-script@v6
        with:
          script: |
            const body = `:hourglass_flowing_sand: Running migration. [View workflow run for details](${context.payload.repository.html_url}/actions/runs/${context.runId})`

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })

      - name: Parse repositories from issue body
        id: parse-issue-body
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            const options = {
              targetOrganization: '${{ vars.GHEC_TARGET_ORGANIZATION }}'
            }
            const parsedIssueBody = require('./.github/scripts/parse-issue-body.js')({github, context, core, options})

            fs.writeFileSync('./repositories.txt', parsedIssueBody.repositories.trim())

      - name: Log repositories to migrate
        run: cat repositories.txt

      - name: Check if repositories exist
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GHEC_ADMIN_TOKEN }}
          script: |
            const options = {
              targetOrganization: '${{ vars.GHEC_TARGET_ORGANIZATION }}',
              repositories: ${{ steps.parse-issue-body.outputs.repositories-json }}
            }

            await require('./.github/scripts/check-existing-repos.js')({github, context, core, options})

      - name: Create empty repositories on GitHub
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GHEC_ADMIN_TOKEN }}
          script: |
            const options = {
              targetOrganization: '${{ vars.GHEC_TARGET_ORGANIZATION }}',
              targetRepositoryVisibility: '${{ steps.parse-issue-body.outputs.target-visibility }}',
              repositories: ${{ steps.parse-issue-body.outputs.repositories-json }}
            }

            await require('./.github/scripts/create-repos.js')({github, context, core, options})

      - name: Clone from Bitbucket Cloud
        run: |
          mkdir -p /tmp/${{ env.MIGRATION_GUID }}

          input="./repositories.txt"
          while IFS= read -r line
          do
            echo "$line"
          done < "$input"

          # Clone repositories
          # cd /tmp/${{ env.MIGRATION_GUID }}
          #git clone https://x-token-auth:${{ secrets.BITBUCKET_CLOUD_ADMIN_TOKEN }}@bitbucket.org/${{ vars.BITBUCKET_CLOUD_WORKSPACE }}/repo0.git

          #ERROR_CODE=$?
          #if [ ${ERROR_CODE} -ne 0 ]; then
          #  # Error
          #  echo "ERROR! Failed to Clone repository:[/${BITBUCKET_URL}/scm/${BITBUCKET_ORG}/${BITBUCKET_REPO}.git]!"
          #  echo "Please verify the URL is reachable, and update variables as needed..."
          #  echo "[${CLONE_CMD}]"
          #  CleanUp
          #  exit 1
          #else
          #  # Success
          #  echo "Successfuly cloned repository:[${BITBUCKET_ORG}/${BITBUCKET_REPO}]"
          #fi

      #- name: Update remote URL
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: ${{ env.MIGRATION_GUID }}.tar.gz
      #    path: ${{ github.workspace }}/${{ env.MIGRATION_GUID }}.tar.gz
      #    if-no-files-found: error
      #    retention-days: 1

      #- if: ${{ failure() }}
      #  name: Update issue with failed export
      #  uses: actions/github-script@v6
      #  with:
      #    script: |
      #      const body = `:no_entry: **Export failed.** [View workflow run for details](${context.payload.repository.html_url}/actions/runs/${context.runId})`

      #      await github.rest.issues.createComment({
      #        issue_number: context.issue.number,
      #        owner: context.repo.owner,
      #        repo: context.repo.repo,
      #        body
      #      })

      #- if: ${{ success() }}
      #  name: Update issue with successful export
      #  uses: actions/github-script@v6
      #  with:
      #    script: |
      #      const body = `:white_check_mark: **Export successful.** [View workflow run for details](${context.payload.repository.html_url}/actions/runs/${context.runId})`

      #      await github.rest.issues.createComment({
      #        issue_number: context.issue.number,
      #        owner: context.repo.owner,
      #        repo: context.repo.repo,
      #        body
      #      })
