name: Migration (Delete repositories)

on:
  issue_comment:
    types: [created]

jobs:
  delete-repositories:
    name: Delete repositories
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'issue_comment' &&
      startsWith(github.event.comment.body, '/delete-repositories')

    defaults:
      run:
        working-directory: tools/ghec-importer

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get migration GUID
        uses: actions/github-script@v6
        id: migration-guid
        with:
          script: |
            const regex = /\/delete-repositories ([^ ]+)/

            const match = context.payload.comment.body.trim().match(regex)

            if (match) {
              console.log('migration-guid', match[1])
              return match[1]
            }

      # Avoid husky from running and failing (.git can't be found) by clearing
      # prepare script npm set-script needs npm > v7
      - name: Install dependencies
        run: |
          npm install -g npm@8
          npm set-script prepare ""
          npm ci --omit=dev

      - name: Link GHEC Importer
        run: npm link

      - name: Delete repositories
        run:
          ghec-importer delete-imported --guid ${{
          steps.migration-guid.outputs.result }} --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHEC_IMPORTER_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
          GHEC_IMPORTER_TARGET_ORGANIZATION:
            ${{ vars.GHEC_TARGET_ORGANIZATION }}

          # Terminate process with non-zero exit code if file system operations
          # fail (https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode)
          NODE_OPTIONS: --unhandled-rejections=strict
