name: Migration from Bitbucket Server

on:
  issues:
    types:
      - opened

jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue body
        run: echo '${{ github.event.issue }}'

  export:
    if: contains(github.event.issue.labels.*.name, 'migration') && contains(github.event.issue.labels.*.name, 'bitbucket-server')
    uses: ./.github/workflows/shared-bitbucket-server-export.yml
    with:
      setup-ruby: true
    secrets:
      BITBUCKET_API_PRIVATE_TOKEN: ${{ secrets.BBS_ADMIN_TOKEN }}
      BITBUCKET_API_ENDPOINT: '${{ secrets.BBS_URL }}/rest/api/latest'

  import:
    needs: export
    uses: ./.github/workflows/shared-github-enterprise-cloud-import.yml
    with:
      user-mappings-path: ../../user-mappings.csv
    secrets:
      BBS_USER_MAPPING_URL: ${{ secrets.BBS_URL }}/users/
      GHEC_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
      GHEC_TARGET_ORGANIZATION: ${{ secrets.GHEC_TARGET_ORGANIZATION }}
